---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: A command-line client for Cloudflare Tunnel
app_name: cloudflared
app_repo: https://github.com/cloudflare/cloudflared
app_type: standalone
app_website: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://api.github.com/repos/cloudflare/cloudflared/releases/tags/{version}
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/cloudflare/cloudflared/releases/download/{version}/cloudflared-{os}-{arch}$(download_ext)
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    cloudflared: bin/cloudflared
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-cloudflared
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-cloudflared.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv5
    armv6*: armv6
    armv7*: armv7
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: ''
